package br.org.ce.senai.VIEW;

import br.org.ce.senai.DAO.ArmazemDAO;
import br.org.ce.senai.DTO.ArmazemDTO;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mateus
 */
public class ArmazemVIEW extends javax.swing.JFrame {

    /**
     * Creates new form ArmazemPrincipalVIEW
     */
    public ArmazemVIEW() {
        initComponents();
        listarArmazensVIEW();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblArmazens = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaArmazens = new javax.swing.JTable();
        btnPesquisarArmazem = new javax.swing.JButton();
        txtPesquisarArmazem = new javax.swing.JTextField();
        btnListarArmazem = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnCadastrarArmazem = new javax.swing.JButton();
        btnEditarArmazem = new javax.swing.JButton();
        btnExcluirArmazem = new javax.swing.JButton();
        lblIDArmazem = new javax.swing.JLabel();
        txtIDArmazem = new javax.swing.JTextField();
        lblNomeArmazem = new javax.swing.JLabel();
        txtNomeArmazem = new javax.swing.JTextField();
        lblEnderecoArmazem = new javax.swing.JLabel();
        txtEnderecoArmazem = new javax.swing.JTextField();
        lblTelefoneArmazem = new javax.swing.JLabel();
        txtTelefoneArmazem = new javax.swing.JTextField();
        btnRetornarPrincipal = new javax.swing.JButton();
        btnCarregarCampos = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        lblDeclaração = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblArmazens.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblArmazens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArmazens.setText("Armazéns");

        tabelaArmazens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Endereço", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaArmazens.setShowGrid(true);
        jScrollPane1.setViewportView(tabelaArmazens);
        if (tabelaArmazens.getColumnModel().getColumnCount() > 0) {
            tabelaArmazens.getColumnModel().getColumn(0).setResizable(false);
            tabelaArmazens.getColumnModel().getColumn(1).setResizable(false);
            tabelaArmazens.getColumnModel().getColumn(2).setResizable(false);
            tabelaArmazens.getColumnModel().getColumn(3).setResizable(false);
        }

        btnPesquisarArmazem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPesquisarArmazem.setText("PESQUISAR");
        btnPesquisarArmazem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarArmazemActionPerformed(evt);
            }
        });

        btnListarArmazem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListarArmazem.setText("LISTAR");
        btnListarArmazem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarArmazemActionPerformed(evt);
            }
        });

        btnCadastrarArmazem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadastrarArmazem.setText("CADASTRAR");
        btnCadastrarArmazem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarArmazemActionPerformed(evt);
            }
        });

        btnEditarArmazem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarArmazem.setText("EDITAR");
        btnEditarArmazem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarArmazemActionPerformed(evt);
            }
        });

        btnExcluirArmazem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluirArmazem.setText("EXCLUIR");
        btnExcluirArmazem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirArmazemActionPerformed(evt);
            }
        });

        lblIDArmazem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIDArmazem.setText("ID");

        txtIDArmazem.setEditable(false);

        lblNomeArmazem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNomeArmazem.setText("Nome");

        lblEnderecoArmazem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEnderecoArmazem.setText("Endereço");

        lblTelefoneArmazem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTelefoneArmazem.setText("Telefone");

        btnRetornarPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRetornarPrincipal.setText("RETORNAR");
        btnRetornarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarPrincipalActionPerformed(evt);
            }
        });

        btnCarregarCampos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarregarCampos.setText("CARREGAR CAMPOS");
        btnCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarCamposActionPerformed(evt);
            }
        });

        btnLimparCampos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimparCampos.setText("LIMPAR CAMPOS");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        lblDeclaração.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblDeclaração.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeclaração.setText("Made by Mat-P1");
        lblDeclaração.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeclaração, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblArmazens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeArmazem)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEnderecoArmazem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEnderecoArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblIDArmazem)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtIDArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(57, 57, 57)
                                            .addComponent(txtNomeArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTelefoneArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTelefoneArmazem))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnExcluirArmazem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCadastrarArmazem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarArmazem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRetornarPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCarregarCampos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimparCampos))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtPesquisarArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisarArmazem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListarArmazem)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblArmazens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDArmazem)
                            .addComponent(txtIDArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeArmazem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnderecoArmazem)
                            .addComponent(txtEnderecoArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefoneArmazem)
                            .addComponent(txtTelefoneArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrarArmazem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarArmazem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirArmazem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRetornarPrincipal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarArmazem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarArmazem)
                    .addComponent(btnPesquisarArmazem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregarCampos)
                    .addComponent(btnLimparCampos))
                .addGap(12, 12, 12)
                .addComponent(lblDeclaração)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarArmazemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarArmazemActionPerformed
        listarArmazensVIEW();
    }//GEN-LAST:event_btnListarArmazemActionPerformed

    private void btnCadastrarArmazemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarArmazemActionPerformed
        cadastrarArmazemVIEW();
        limparCampos();
        listarArmazensVIEW();
    }//GEN-LAST:event_btnCadastrarArmazemActionPerformed

    private void btnRetornarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarPrincipalActionPerformed
        TelaPrincipalVIEW objTelaPrincipalVIEW = new TelaPrincipalVIEW();
        objTelaPrincipalVIEW.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRetornarPrincipalActionPerformed

    private void btnPesquisarArmazemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarArmazemActionPerformed
        String pesquisar = txtPesquisarArmazem.getText();
        pesquisarArmazemVIEW(pesquisar);
    }//GEN-LAST:event_btnPesquisarArmazemActionPerformed

    private void btnCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarCamposActionPerformed
        carregarCampos();
    }//GEN-LAST:event_btnCarregarCamposActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnEditarArmazemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarArmazemActionPerformed
        alterarArmazemVIEW();
        listarArmazensVIEW();
    }//GEN-LAST:event_btnEditarArmazemActionPerformed

    private void btnExcluirArmazemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirArmazemActionPerformed
        excluirArmazemVIEW();
        limparCampos();
        listarArmazensVIEW();
    }//GEN-LAST:event_btnExcluirArmazemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArmazemVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArmazemVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArmazemVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArmazemVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArmazemVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarArmazem;
    private javax.swing.JButton btnCarregarCampos;
    private javax.swing.JButton btnEditarArmazem;
    private javax.swing.JButton btnExcluirArmazem;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnListarArmazem;
    private javax.swing.JButton btnPesquisarArmazem;
    private javax.swing.JButton btnRetornarPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblArmazens;
    private javax.swing.JLabel lblDeclaração;
    private javax.swing.JLabel lblEnderecoArmazem;
    private javax.swing.JLabel lblIDArmazem;
    private javax.swing.JLabel lblNomeArmazem;
    private javax.swing.JLabel lblTelefoneArmazem;
    private javax.swing.JTable tabelaArmazens;
    private javax.swing.JTextField txtEnderecoArmazem;
    private javax.swing.JTextField txtIDArmazem;
    private javax.swing.JTextField txtNomeArmazem;
    private javax.swing.JTextField txtPesquisarArmazem;
    private javax.swing.JTextField txtTelefoneArmazem;
    // End of variables declaration//GEN-END:variables
    
    private void limparCampos() {
        txtPesquisarArmazem.setText("");
        txtIDArmazem.setText("");
        txtNomeArmazem.setText("");
        txtEnderecoArmazem.setText("");
        txtTelefoneArmazem.setText("");
    }
    
    private void carregarCampos() {
        int setarCampo = tabelaArmazens.getSelectedRow();
        
        txtIDArmazem.setText(tabelaArmazens.getModel().getValueAt(setarCampo, 0).toString());
        txtNomeArmazem.setText(tabelaArmazens.getModel().getValueAt(setarCampo, 1).toString());
        txtEnderecoArmazem.setText(tabelaArmazens.getModel().getValueAt(setarCampo, 2).toString());
        txtTelefoneArmazem.setText(tabelaArmazens.getModel().getValueAt(setarCampo, 3).toString());
    }
     
     private void cadastrarArmazemVIEW() {
        try {
            String nomeArmazemVIEW = txtNomeArmazem.getText();
            String enderecoArmazemVIEW = txtEnderecoArmazem.getText();
            String telefoneArmazemVIEW = txtTelefoneArmazem.getText();
        
            ArmazemDTO objArmazemDTO = new ArmazemDTO();
        
            objArmazemDTO.setNomeArmazemDTO(nomeArmazemVIEW);
            objArmazemDTO.setEnderecoArmazemDTO(enderecoArmazemVIEW);
            objArmazemDTO.setTelefoneArmazemDTO(telefoneArmazemVIEW);
        
            ArmazemDAO objArmazemDAO = new ArmazemDAO();
            objArmazemDAO.cadastrarArmazemDAO(objArmazemDTO);
            
         } catch (Exception error) {
             JOptionPane.showMessageDialog(null, "Error\ncadastrarArmazemVIEW" + error);
         }
    }   
        
    private void listarArmazensVIEW() {
        try {
            ArmazemDAO objArmazemDAO = new ArmazemDAO();
            
            DefaultTableModel model = (DefaultTableModel) tabelaArmazens.getModel();         
            model.setNumRows(0);
            
            ArrayList<ArmazemDTO> listaArmazens = objArmazemDAO.listarArmazensDAO();
            
            for (int i = 0; i < listaArmazens.size(); i++) {
                model.addRow(new Object[]{
                        listaArmazens.get(i).getIdArmazemDTO(),
                        listaArmazens.get(i).getNomeArmazemDTO(),
                        listaArmazens.get(i).getEnderecoArmazemDTO(),
                        listaArmazens.get(i).getTelefoneArmazemDTO(),
                });
            } 
            
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Erro\nlistarArmazensVIEW" + error);
        }
    }
    
    private void pesquisarArmazemVIEW(String descricao) {
        try {
            ArmazemDAO objArmazemDAO = new ArmazemDAO();
            
            DefaultTableModel model = (DefaultTableModel) tabelaArmazens.getModel();         
            model.setNumRows(0);
            
            ArrayList<ArmazemDTO> pesquisarArmazens = objArmazemDAO.pesquisarArmazemDAO(descricao);
            
            for (int i = 0; i < pesquisarArmazens.size(); i++) {
                model.addRow(new Object[]{
                        pesquisarArmazens.get(i).getIdArmazemDTO(),
                        pesquisarArmazens.get(i).getNomeArmazemDTO(),
                        pesquisarArmazens.get(i).getEnderecoArmazemDTO(),
                        pesquisarArmazens.get(i).getTelefoneArmazemDTO(),
                });
            } 
            
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Erro\npesquisarArmazemVIEW" + error);
        }
    }
    
    private void alterarArmazemVIEW() { 
        try {
            int idArmazemVIEW = Integer.parseInt(txtIDArmazem.getText());
            String nomeArmazemDTO = txtNomeArmazem.getText();
            String enderecoArmazemDTO = txtEnderecoArmazem.getText();
            String telefoneArmazemDTO = txtTelefoneArmazem.getText();
        
            ArmazemDTO objArmazemDTO = new ArmazemDTO();
            objArmazemDTO.setIdArmazemDTO(idArmazemVIEW);
            objArmazemDTO.setNomeArmazemDTO(nomeArmazemDTO);
            objArmazemDTO.setEnderecoArmazemDTO(enderecoArmazemDTO);
            objArmazemDTO.setTelefoneArmazemDTO(telefoneArmazemDTO);
        
            ArmazemDAO objArmazemDAO = new ArmazemDAO();
            objArmazemDAO.alterarArmazemDAO(objArmazemDTO);
            
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(null, "Erro\nalterarArmazemVIEW" + error);
        }     
    }
    
    private void excluirArmazemVIEW() {     
        try {
           int idArmazemVIEW = Integer.parseInt(txtIDArmazem.getText());
           
           ArmazemDTO objArmazemDTO = new ArmazemDTO();
           objArmazemDTO.setIdArmazemDTO(idArmazemVIEW);
           
           ArmazemDAO objArmazemDAO = new ArmazemDAO();
           objArmazemDAO.excluirArmazemDAO(objArmazemDTO);
           
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(null, "Erro\nexcluirArmazemVIEW" + error);
        }
    }
}
