package br.org.ce.senai.VIEW;

import br.org.ce.senai.DAO.FuncionarioDAO;
import br.org.ce.senai.DTO.FuncionarioDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mateus
 */
public class FuncionarioVIEW extends javax.swing.JFrame {

    /**
     * Creates new form FuncionarioVIEW
     */
    public FuncionarioVIEW() {
        initComponents();
        listarFuncionariosVIEW();
        listarArmazensFuncionarioVIEW();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFuncionarios = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblIDFuncionario = new javax.swing.JLabel();
        txtIDFuncionario = new javax.swing.JTextField();
        lblCPFFuncionario = new javax.swing.JLabel();
        txtCPFFuncionario = new javax.swing.JTextField();
        lblNomeFuncionario = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        lblFuncaoFuncionario = new javax.swing.JLabel();
        txtFuncaoFuncionario = new javax.swing.JTextField();
        btnCadastrarFuncionario = new javax.swing.JButton();
        btnEditarFuncionario = new javax.swing.JButton();
        btnExcluirFuncionario = new javax.swing.JButton();
        btnRetornarPrincipal = new javax.swing.JButton();
        txtPesquisarFuncionario = new javax.swing.JTextField();
        btnPesquisarFuncionario = new javax.swing.JButton();
        btnListarFuncionarios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionarios = new javax.swing.JTable();
        btnCarregarCampos = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        lblDeclaração = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblSalarioFuncionario = new javax.swing.JLabel();
        txtSalarioFuncionario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbxArmazemFuncionario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFuncionarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFuncionarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFuncionarios.setText("Funcionários");

        lblIDFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIDFuncionario.setText("ID");

        txtIDFuncionario.setEditable(false);
        txtIDFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDFuncionarioActionPerformed(evt);
            }
        });

        lblCPFFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCPFFuncionario.setText("CPF");

        lblNomeFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNomeFuncionario.setText("Nome");

        lblFuncaoFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFuncaoFuncionario.setText("Função");

        btnCadastrarFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadastrarFuncionario.setText("CADASTRAR");
        btnCadastrarFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFuncionarioActionPerformed(evt);
            }
        });

        btnEditarFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarFuncionario.setText("EDITAR");
        btnEditarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFuncionarioActionPerformed(evt);
            }
        });

        btnExcluirFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluirFuncionario.setText("EXCLUIR");
        btnExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirFuncionarioActionPerformed(evt);
            }
        });

        btnRetornarPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRetornarPrincipal.setText("RETORNAR");
        btnRetornarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarPrincipalActionPerformed(evt);
            }
        });

        btnPesquisarFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPesquisarFuncionario.setText("PESQUISAR");
        btnPesquisarFuncionario.setToolTipText("");
        btnPesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarFuncionarioActionPerformed(evt);
            }
        });

        btnListarFuncionarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListarFuncionarios.setText("LISTAR");
        btnListarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarFuncionariosActionPerformed(evt);
            }
        });

        tabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CPF", "Nome", "Funçao", "Salário", "Armazém"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFuncionarios.setShowGrid(true);
        jScrollPane1.setViewportView(tabelaFuncionarios);

        btnCarregarCampos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarregarCampos.setText("CARREGAR CAMPOS");
        btnCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarCamposActionPerformed(evt);
            }
        });

        btnLimparCampos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimparCampos.setText("LIMPAR CAMPOS");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        lblDeclaração.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblDeclaração.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeclaração.setText("Made by Mat-P1");
        lblDeclaração.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSalarioFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSalarioFuncionario.setText("Salário");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Armazém");

        cbxArmazemFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDeclaração, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(btnCarregarCampos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimparCampos))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtPesquisarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListarFuncionarios)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCPFFuncionario)
                                            .addComponent(lblIDFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCPFFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(txtIDFuncionario)
                                            .addComponent(txtNomeFuncionario)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFuncaoFuncionario)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFuncaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCadastrarFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEditarFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnExcluirFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRetornarPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jSeparator3))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxArmazemFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSalarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSalarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDFuncionario)
                    .addComponent(txtIDFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFFuncionario)
                    .addComponent(txtCPFFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFuncionario)
                    .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncaoFuncionario)
                    .addComponent(txtFuncaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetornarPrincipal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalarioFuncionario)
                    .addComponent(txtSalarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxArmazemFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarFuncionario)
                    .addComponent(btnListarFuncionarios))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregarCampos)
                    .addComponent(btnLimparCampos))
                .addGap(18, 18, 18)
                .addComponent(lblDeclaração)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncionarioActionPerformed
        cadastarFuncionarioVIEW();
        limparCampos();
        listarFuncionariosVIEW();
    }//GEN-LAST:event_btnCadastrarFuncionarioActionPerformed

    private void btnListarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarFuncionariosActionPerformed
        listarFuncionariosVIEW();
    }//GEN-LAST:event_btnListarFuncionariosActionPerformed

    private void btnPesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarFuncionarioActionPerformed
        String descricao = txtPesquisarFuncionario.getText();
        pesquisarFuncionariosVIEW(descricao);
    }//GEN-LAST:event_btnPesquisarFuncionarioActionPerformed

    private void btnEditarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFuncionarioActionPerformed
        alterarFuncionario();
        listarFuncionariosVIEW();
    }//GEN-LAST:event_btnEditarFuncionarioActionPerformed

    private void btnExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFuncionarioActionPerformed
        excluirFuncionario();
        limparCampos();
        listarFuncionariosVIEW();
    }//GEN-LAST:event_btnExcluirFuncionarioActionPerformed

    private void btnCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarCamposActionPerformed
        carregarCampos();
    }//GEN-LAST:event_btnCarregarCamposActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnRetornarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarPrincipalActionPerformed
        TelaPrincipalVIEW objTelaPrincipalVIEW = new TelaPrincipalVIEW();
        objTelaPrincipalVIEW.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRetornarPrincipalActionPerformed

    private void txtIDFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDFuncionarioActionPerformed
       
    }//GEN-LAST:event_txtIDFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarFuncionario;
    private javax.swing.JButton btnCarregarCampos;
    private javax.swing.JButton btnEditarFuncionario;
    private javax.swing.JButton btnExcluirFuncionario;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnListarFuncionarios;
    private javax.swing.JButton btnPesquisarFuncionario;
    private javax.swing.JButton btnRetornarPrincipal;
    private javax.swing.JComboBox<String> cbxArmazemFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCPFFuncionario;
    private javax.swing.JLabel lblDeclaração;
    private javax.swing.JLabel lblFuncaoFuncionario;
    private javax.swing.JLabel lblFuncionarios;
    private javax.swing.JLabel lblIDFuncionario;
    private javax.swing.JLabel lblNomeFuncionario;
    private javax.swing.JLabel lblSalarioFuncionario;
    private javax.swing.JTable tabelaFuncionarios;
    private javax.swing.JTextField txtCPFFuncionario;
    private javax.swing.JTextField txtFuncaoFuncionario;
    private javax.swing.JTextField txtIDFuncionario;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtPesquisarFuncionario;
    private javax.swing.JTextField txtSalarioFuncionario;
    // End of variables declaration//GEN-END:variables

    ArrayList<Integer> idArmazemFuncionario = new ArrayList<>();
    
    private void limparCampos() {
        txtIDFuncionario.setText("");
        txtCPFFuncionario.setText("");
        txtNomeFuncionario.setText("");
        txtFuncaoFuncionario.setText("");
        txtSalarioFuncionario.setText("");
    }
    
    private void carregarCampos() {
        int setarCampos = tabelaFuncionarios.getSelectedRow();
        
        txtIDFuncionario.setText(tabelaFuncionarios.getModel().getValueAt(setarCampos, 0).toString());
        txtCPFFuncionario.setText(tabelaFuncionarios.getModel().getValueAt(setarCampos, 1).toString());
        txtNomeFuncionario.setText(tabelaFuncionarios.getModel().getValueAt(setarCampos, 2).toString());
        txtFuncaoFuncionario.setText(tabelaFuncionarios.getModel().getValueAt(setarCampos, 3).toString());
        txtSalarioFuncionario.setText(tabelaFuncionarios.getModel().getValueAt(setarCampos, 4).toString());
    }
       
    private void listarArmazensFuncionarioVIEW() {
        
        try {
            FuncionarioDAO objFuncionarioDAO = new FuncionarioDAO();
            ResultSet rs = objFuncionarioDAO.listarArmazensFuncionarioDAO();
            
            while(rs.next()) {
                idArmazemFuncionario.add(rs.getInt(1));
                cbxArmazemFuncionario.addItem(rs.getString(2));
            }
            
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Error\nlistarArmazensFuncionarioVIEW" + error);
        }
    }
    
    private void cadastarFuncionarioVIEW() {
        try {
            Long CPFVIEW = Long.valueOf(txtCPFFuncionario.getText());
            String nomeFuncionarioVIEW = txtNomeFuncionario.getText();
            String funcaoFuncionarioVIEW = txtFuncaoFuncionario.getText();
            double salarioFuncionarioVIEW = Double.parseDouble(txtSalarioFuncionario.getText());
            int idArmazemFuncionarioVIEW = idArmazemFuncionario.get(cbxArmazemFuncionario.getSelectedIndex() - 1);
                    
            FuncionarioDTO objFuncionarioDTO = new FuncionarioDTO();
            
            objFuncionarioDTO.setCPFDTO(CPFVIEW);
            objFuncionarioDTO.setNomeFuncionarioDTO(nomeFuncionarioVIEW);
            objFuncionarioDTO.setFuncaoFuncionarioDTO(funcaoFuncionarioVIEW);
            objFuncionarioDTO.setSalarioFuncionarioDTO(salarioFuncionarioVIEW);
            objFuncionarioDTO.setIdArmazemFuncionarioDTO(idArmazemFuncionarioVIEW);
            
            FuncionarioDAO objFuncionarioDAO = new FuncionarioDAO();
            
            objFuncionarioDAO.cadastrarFuncionarioDAO(objFuncionarioDTO);
            
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(null, "Error\ncadastrarFuncionarioVIEW" + error);
        }
    }
    
    private void listarFuncionariosVIEW() {
        try {
            FuncionarioDAO objFuncionarioDAO = new FuncionarioDAO();
            
            DefaultTableModel model = (DefaultTableModel) tabelaFuncionarios.getModel();
            model.setNumRows(0);
            
            ArrayList<FuncionarioDTO>listaFuncionarios = objFuncionarioDAO.listarFuncionariosDAO();
            
            for (int i = 0; i < listaFuncionarios.size(); i++) {
                model.addRow(new Object[]{
                    listaFuncionarios.get(i).getIdFuncionarioDTO(),
                    listaFuncionarios.get(i).getCPFDTO(),
                    listaFuncionarios.get(i).getNomeFuncionarioDTO(),
                    listaFuncionarios.get(i).getFuncaoFuncionarioDTO(),
                    listaFuncionarios.get(i).getSalarioFuncionarioDTO(),
                    listaFuncionarios.get(i).getIdArmazemFuncionarioDTO(),
                });
            }
            
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Error\nlistarFuncionarioVIEW" + error);
        }
    }
    
    private void pesquisarFuncionariosVIEW(String descricao) {
        try {
            FuncionarioDAO objFuncionarioDAO = new FuncionarioDAO();
            
            DefaultTableModel model = (DefaultTableModel) tabelaFuncionarios.getModel();
            model.setNumRows(0);
            
            ArrayList<FuncionarioDTO>pesquisarFuncionario = objFuncionarioDAO.pesquisarFuncionarioDAO(descricao);
            
            for (int i = 0; i < pesquisarFuncionario.size(); i++) {
                model.addRow(new Object[]{
                    pesquisarFuncionario.get(i).getIdFuncionarioDTO(),
                    pesquisarFuncionario.get(i).getCPFDTO(),
                    pesquisarFuncionario.get(i).getNomeFuncionarioDTO(),
                    pesquisarFuncionario.get(i).getFuncaoFuncionarioDTO(),
                    pesquisarFuncionario.get(i).getSalarioFuncionarioDTO(),
                    pesquisarFuncionario.get(i).getIdArmazemFuncionarioDTO(),
                });
            }
            
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Error\npesquisarFuncionarioVIEW" + error);
        }
    }
    
    private void alterarFuncionario() {
        try {
            int idFuncionarioVIEW = Integer.parseInt(txtIDFuncionario.getText());
            Long CPFVIEW = Long.valueOf(txtCPFFuncionario.getText());
            String nomeFuncionarioVIEW = txtNomeFuncionario.getText();
            String funcaoFuncionarioVIEW = txtFuncaoFuncionario.getText();
            double salarioFuncionarioVIEW = Double.parseDouble(txtSalarioFuncionario.getText());
            int idArmazemFuncionarioVIEW = idArmazemFuncionario.get(cbxArmazemFuncionario.getSelectedIndex() - 1);
            
            FuncionarioDTO objFuncionarioDTO = new FuncionarioDTO();
            
            objFuncionarioDTO.setIdFuncionarioDTO(idFuncionarioVIEW);
            objFuncionarioDTO.setCPFDTO(CPFVIEW);
            objFuncionarioDTO.setNomeFuncionarioDTO(nomeFuncionarioVIEW);
            objFuncionarioDTO.setFuncaoFuncionarioDTO(funcaoFuncionarioVIEW);
            objFuncionarioDTO.setSalarioFuncionarioDTO(salarioFuncionarioVIEW);
            objFuncionarioDTO.setIdArmazemFuncionarioDTO(idArmazemFuncionarioVIEW);
            
            FuncionarioDAO objFuncionarioDAO = new FuncionarioDAO();
            
            objFuncionarioDAO.alterarFuncionarioDAO(objFuncionarioDTO);
                      
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(null, "Error\nalterarFuncionarioVIEW" + error); 
        }
    }
    
    private void excluirFuncionario() {
        try {
            int idFuncionarioVIEW = Integer.parseInt(txtIDFuncionario.getText());
            
            FuncionarioDTO objFuncionarioDTO = new FuncionarioDTO(); 
            
            objFuncionarioDTO.setIdFuncionarioDTO(idFuncionarioVIEW);
            
            FuncionarioDAO objFuncionarioDAO = new FuncionarioDAO();  
            
            objFuncionarioDAO.excluirFuncionarioDAO(objFuncionarioDTO);
                      
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(null, "Error\nexcluirFuncionarioVIEW" + error); 
        }
    }
}
