package br.org.ce.senai.VIEW;

import br.org.ce.senai.DAO.ProdutoDAO;
import br.org.ce.senai.DTO.ProdutoDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mateus
 */
public class ProdutoVIEW extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoVIEW
     */
    public ProdutoVIEW() {
        initComponents();
        listarProdutosVIEW();
        listarArmazensProdutoVIEW();
        listarFornecedoresProdutoVIEW();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProdutosVIEW = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblIDProduto = new javax.swing.JLabel();
        lblNumeroProduto = new javax.swing.JLabel();
        lblNomeProduto = new javax.swing.JLabel();
        lblValorProduto = new javax.swing.JLabel();
        lblQTDProduto = new javax.swing.JLabel();
        lblEntregaProduto = new javax.swing.JLabel();
        lblFornecedorProduto = new javax.swing.JLabel();
        lblArmazemProduto = new javax.swing.JLabel();
        txtNumeroProduto = new javax.swing.JTextField();
        txtQTDProduto = new javax.swing.JTextField();
        txtNomeProduto = new javax.swing.JTextField();
        txtValorProduto = new javax.swing.JTextField();
        txtDataProduto = new javax.swing.JTextField();
        cbxArmazemProduto = new javax.swing.JComboBox<>();
        cbxFornecedorProduto = new javax.swing.JComboBox<>();
        btnCadastrarProduto = new javax.swing.JButton();
        btnEditarProduto = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        btnRetornarPrincipal = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtPesquisarProduto = new javax.swing.JTextField();
        btnPesquisarProduto = new javax.swing.JButton();
        btnListarProdutos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        btnCarregarCampos = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIDProduto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProdutosVIEW.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblProdutosVIEW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProdutosVIEW.setText("Produtos");
        lblProdutosVIEW.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblIDProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIDProduto.setText("ID");

        lblNumeroProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumeroProduto.setText("Número");

        lblNomeProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNomeProduto.setText("Nome");

        lblValorProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValorProduto.setText("Valor");

        lblQTDProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQTDProduto.setText("Quantidade");

        lblEntregaProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEntregaProduto.setText("Entrega");

        lblFornecedorProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFornecedorProduto.setText("Fornecedor");

        lblArmazemProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblArmazemProduto.setText("Armazém");

        cbxArmazemProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        cbxFornecedorProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        btnCadastrarProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadastrarProduto.setText("CADASTRAR");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        btnEditarProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarProduto.setText("EDITAR");
        btnEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProdutoActionPerformed(evt);
            }
        });

        btnExcluirProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluirProduto.setText("EXCLUIR");
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });

        btnRetornarPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRetornarPrincipal.setText("RETORNAR");
        btnRetornarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarPrincipalActionPerformed(evt);
            }
        });

        btnPesquisarProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPesquisarProduto.setText("PESQUISAR");
        btnPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdutoActionPerformed(evt);
            }
        });

        btnListarProdutos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListarProdutos.setText("LISTAR");
        btnListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProdutosActionPerformed(evt);
            }
        });

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Número", "Nome", "Valor", "Quantidade", "Entrega", "Armazém", "Fornecedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.setShowGrid(true);
        jScrollPane1.setViewportView(tabelaProdutos);

        btnCarregarCampos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarregarCampos.setText("CARREAGR CAMPOS");
        btnCarregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarCamposActionPerformed(evt);
            }
        });

        btnLimparCampos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimparCampos.setText("LIMPAR CAMPOS");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Made by Mat-P1");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtIDProduto.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(lblProdutosVIEW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumeroProduto)
                                    .addComponent(lblNomeProduto)
                                    .addComponent(lblIDProduto))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNomeProduto)
                                        .addComponent(txtNumeroProduto)
                                        .addComponent(txtIDProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                    .addComponent(txtValorProduto)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQTDProduto)
                                    .addComponent(lblValorProduto)
                                    .addComponent(lblEntregaProduto)
                                    .addComponent(lblArmazemProduto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDataProduto)
                                    .addComponent(txtQTDProduto)
                                    .addComponent(cbxArmazemProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxFornecedorProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrarProduto)
                            .addComponent(btnEditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRetornarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListarProdutos))
                            .addComponent(lblFornecedorProduto))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCarregarCampos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimparCampos)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProdutosVIEW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIDProduto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadastrarProduto)
                        .addComponent(txtIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarProduto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumeroProduto)
                        .addComponent(txtNumeroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeProduto)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorProduto)
                    .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetornarPrincipal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQTDProduto)
                    .addComponent(txtQTDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEntregaProduto)
                    .addComponent(txtDataProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArmazemProduto)
                    .addComponent(cbxArmazemProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorProduto)
                    .addComponent(cbxFornecedorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarProduto)
                    .addComponent(btnListarProdutos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregarCampos)
                    .addComponent(btnLimparCampos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        cadastrarProdutoVIEW();
        listarProdutosVIEW();
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void btnListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProdutosActionPerformed
        listarProdutosVIEW();
    }//GEN-LAST:event_btnListarProdutosActionPerformed

    private void btnPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdutoActionPerformed
        String descricao = txtPesquisarProduto.getText();
        pesquisarProdutoVIEW(descricao);
    }//GEN-LAST:event_btnPesquisarProdutoActionPerformed

    private void btnEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProdutoActionPerformed
        alterarProdutoVIEW();
        listarProdutosVIEW();
    }//GEN-LAST:event_btnEditarProdutoActionPerformed

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        excluirProdutoVIEW();
        limparCampos();
        listarProdutosVIEW();
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void btnCarregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarCamposActionPerformed
        carregarCampos();
    }//GEN-LAST:event_btnCarregarCamposActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnRetornarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarPrincipalActionPerformed
        TelaPrincipalVIEW objTelaPrincipalVIEW = new TelaPrincipalVIEW();
        objTelaPrincipalVIEW.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRetornarPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnCarregarCampos;
    private javax.swing.JButton btnEditarProduto;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnListarProdutos;
    private javax.swing.JButton btnPesquisarProduto;
    private javax.swing.JButton btnRetornarPrincipal;
    private javax.swing.JComboBox<String> cbxArmazemProduto;
    private javax.swing.JComboBox<String> cbxFornecedorProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblArmazemProduto;
    private javax.swing.JLabel lblEntregaProduto;
    private javax.swing.JLabel lblFornecedorProduto;
    private javax.swing.JLabel lblIDProduto;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblNumeroProduto;
    private javax.swing.JLabel lblProdutosVIEW;
    private javax.swing.JLabel lblQTDProduto;
    private javax.swing.JLabel lblValorProduto;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTextField txtDataProduto;
    private javax.swing.JTextField txtIDProduto;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtNumeroProduto;
    private javax.swing.JTextField txtPesquisarProduto;
    private javax.swing.JTextField txtQTDProduto;
    private javax.swing.JTextField txtValorProduto;
    // End of variables declaration//GEN-END:variables
    
    ArrayList<Integer> IdArmazemProduto = new ArrayList<>();
    ArrayList<Integer> IdFornecedorProduto = new ArrayList<>();
    
    private void carregarCampos() {
        int setarCampos = tabelaProdutos.getSelectedRow();
        
        txtIDProduto.setText(tabelaProdutos.getModel().getValueAt(setarCampos, 0).toString());
        txtNumeroProduto.setText(tabelaProdutos.getModel().getValueAt(setarCampos, 1).toString());
        txtNomeProduto.setText(tabelaProdutos.getModel().getValueAt(setarCampos, 2).toString());
        txtValorProduto.setText(tabelaProdutos.getModel().getValueAt(setarCampos, 3).toString());
        txtQTDProduto.setText(tabelaProdutos.getModel().getValueAt(setarCampos, 4).toString());
        txtDataProduto.setText(tabelaProdutos.getModel().getValueAt(setarCampos, 5).toString());
    }
    
    private void limparCampos() {
        txtIDProduto.setText("");
        txtNumeroProduto.setText("");
        txtNomeProduto.setText("");
        txtValorProduto.setText("");
        txtQTDProduto.setText("");
        txtDataProduto.setText("");
    }
    
    private void listarArmazensProdutoVIEW() {
        try {
            ProdutoDAO objProdutoDAO = new ProdutoDAO();
            ResultSet rs = objProdutoDAO.listarArmazensProdutoDAO();
            
            while(rs.next()) {
                IdArmazemProduto.add(rs.getInt(1));
                cbxArmazemProduto.addItem(rs.getString(2));
            }
            
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Error\nlistarArmazensProdutoVIEW" + error);
        }
    }
    
    private void listarFornecedoresProdutoVIEW() {
        try {
            ProdutoDAO objProdutoDAO = new ProdutoDAO();
            ResultSet rs = objProdutoDAO.listarFornecedoresProdutoDAO();
            
            while(rs.next()) {
                IdFornecedorProduto.add(rs.getInt(1));
                cbxFornecedorProduto.addItem(rs.getString(3));
            }
            
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Error\nlistarFornecedoresProdutoVIEW" + error);
        }
    }
    
    private void cadastrarProdutoVIEW() {
        try {
            String numeroSeriaProdutolVIEW = txtNumeroProduto.getText();
            String nomeProdutoVIEW = txtNomeProduto.getText();
            double valorProdutoVIEW = Double.parseDouble(txtValorProduto.getText());
            int qtdProdutoVIEW = Integer.parseInt(txtQTDProduto.getText());
            String dataEntregaProdutoVIEW = (txtDataProduto.getText());
            int idArmazemProdutoVIEW = IdArmazemProduto.get(cbxArmazemProduto.getSelectedIndex() - 1);
            int idFornecedorProdutoVIEW = IdFornecedorProduto.get(cbxFornecedorProduto.getSelectedIndex() - 1);
            
            ProdutoDTO objProdutoDTO = new ProdutoDTO();
            
            objProdutoDTO.setNumeroSerialProdutoDTO(numeroSeriaProdutolVIEW);
            objProdutoDTO.setNomeProdutoDTO(nomeProdutoVIEW);
            objProdutoDTO.setValorProdutoDTO(valorProdutoVIEW);
            objProdutoDTO.setQtdProdutoDTO(qtdProdutoVIEW);
            objProdutoDTO.setDataEntregaProdutoDTO(dataEntregaProdutoVIEW);
            objProdutoDTO.setIdArmazemProdutoDTO(idArmazemProdutoVIEW);
            objProdutoDTO.setIdFornecedorProdutoDTO(idFornecedorProdutoVIEW);
            
            ProdutoDAO objProdutoDAO = new ProdutoDAO();
            
            objProdutoDAO.cadastrarProdutoDAO(objProdutoDTO);
            
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(null, "Error\ncadastrarProdutoVIEW" + error);
        }
    }
    
    private void listarProdutosVIEW() {
        try {
            ProdutoDAO objProdutoDAO = new ProdutoDAO();
            
            DefaultTableModel model = (DefaultTableModel) tabelaProdutos.getModel();
            model.setNumRows(0);
            
            ArrayList<ProdutoDTO>listaProdutos = objProdutoDAO.listarProdutosDAO();
            
            for (int i = 0; i < listaProdutos.size(); i++) {
                model.addRow(new Object[]{
                    listaProdutos.get(i).getIdProdutoDTO(),
                    listaProdutos.get(i).getNumeroSerialProdutoDTO(),
                    listaProdutos.get(i).getNomeProdutoDTO(),
                    listaProdutos.get(i).getValorProdutoDTO(),
                    listaProdutos.get(i).getQtdProdutoDTO(),
                    listaProdutos.get(i).getDataEntregaProdutoDTO(),
                    listaProdutos.get(i).getIdArmazemProdutoDTO(),
                    listaProdutos.get(i).getIdFornecedorProdutoDTO(),
                });
            }
            
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Error\nlistarProdutosVIEW" + error);
        }
    }
    
    private void pesquisarProdutoVIEW(String descricao) {
        try {
            ProdutoDAO objProdutoDAO = new ProdutoDAO();
            
            DefaultTableModel model = (DefaultTableModel) tabelaProdutos.getModel();
            model.setNumRows(0);
            
            ArrayList<ProdutoDTO>listaProdutos = objProdutoDAO.pesquisarProdutoDAO(descricao);
            
            for (int i = 0; i < listaProdutos.size(); i++) {
                model.addRow(new Object[]{
                    listaProdutos.get(i).getIdProdutoDTO(),
                    listaProdutos.get(i).getNumeroSerialProdutoDTO(),
                    listaProdutos.get(i).getNomeProdutoDTO(),
                    listaProdutos.get(i).getValorProdutoDTO(),
                    listaProdutos.get(i).getQtdProdutoDTO(),
                    listaProdutos.get(i).getDataEntregaProdutoDTO(),
                    listaProdutos.get(i).getIdArmazemProdutoDTO(),
                    listaProdutos.get(i).getIdFornecedorProdutoDTO(),
                });
            }
            
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Error\npesquisarProdutoVIEW" + error);
        }
    }
    
    private void alterarProdutoVIEW() {
        try {
            int idProdutoVIEW = Integer.parseInt(txtIDProduto.getText());
            String numeroSeriaProdutolVIEW = txtNumeroProduto.getText();
            String nomeProdutoVIEW = txtNomeProduto.getText();
            double valorProdutoVIEW = Double.parseDouble(txtValorProduto.getText());
            int qtdProdutoVIEW = Integer.parseInt(txtQTDProduto.getText());
            String dataEntregaProdutoVIEW = (txtDataProduto.getText());
            int idArmazemProdutoVIEW = IdArmazemProduto.get(cbxArmazemProduto.getSelectedIndex() - 1);
            int idFornecedorProdutoVIEW = IdFornecedorProduto.get(cbxFornecedorProduto.getSelectedIndex() - 1);
            
            ProdutoDTO objProdutoDTO = new ProdutoDTO();
            
            objProdutoDTO.setIdProdutoDTO(idProdutoVIEW);
            objProdutoDTO.setNumeroSerialProdutoDTO(numeroSeriaProdutolVIEW);
            objProdutoDTO.setNomeProdutoDTO(nomeProdutoVIEW);
            objProdutoDTO.setValorProdutoDTO(valorProdutoVIEW);
            objProdutoDTO.setQtdProdutoDTO(qtdProdutoVIEW);
            objProdutoDTO.setDataEntregaProdutoDTO(dataEntregaProdutoVIEW);
            objProdutoDTO.setIdArmazemProdutoDTO(idArmazemProdutoVIEW);
            objProdutoDTO.setIdFornecedorProdutoDTO(idFornecedorProdutoVIEW);
            
            ProdutoDAO objProdutoDAO = new ProdutoDAO();
            
            objProdutoDAO.alterarProdutoDAO(objProdutoDTO);
            
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(null, "Error\nalterarProdutoVIEW()" + error);
        }
    }
    
    private void excluirProdutoVIEW() {
        try {
            int idProdutoVIEW = Integer.parseInt(txtIDProduto.getText());
            
            ProdutoDTO objProdutoDTO = new ProdutoDTO();
            
            objProdutoDTO.setIdProdutoDTO(idProdutoVIEW);
            
            ProdutoDAO objProdutoDAO = new ProdutoDAO();
            
            objProdutoDAO.excluirProdutoDAO(objProdutoDTO);
            
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(null, "Error\nexcluirProdutoVIEW()" + error);
        }
    }
}
